# Generated by Django 5.0 on 2023-12-20 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mock_tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mocktest",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=list,
                size=8,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=list,
                size=4,
            ),
        ),
    ]
