# Generated by Django 5.0 on 2023-12-20 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="skills_taught",
        ),
    ]
