# Generated by Django 5.0 on 2023-12-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_skills_taught"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="skills_taught",
            field=models.ManyToManyField(to="courses.skill"),
        ),
    ]
