# Generated by Django 5.0 on 2023-12-20 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_skills_taught"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="skills_taught",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="course",
            name="skills_taught",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=10),
                default=[],
                size=8,
            ),
        ),
    ]
