# Generated by Django 5.0 on 2023-12-20 07:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_course_skills_taught_delete_skill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="skills_taught",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=[],
                size=8,
            ),
        ),
    ]
