# Generated by Django 5.0 on 2023-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="disability_category",
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="no_posts",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
